### ISSUE TITLE
Manage all passwords; centralized access

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#10]

**Comment by B3NLADEN** [comment]
this should be fairly straight forward; busy work i believe

**Comment by domhoward14** [comment]
After we get a domain name for our website (Which should be beginning of next year) we can use a central email address to make a [LastPass account (Password Manager).](lastpass.com)

**Comment by B3NLADEN** [comment]
created a breakdown of cost; search for the epic
