### ISSUE TITLE
Write a purposeful 1st blog Entry

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#11]

**Comment by B3NLADEN** [comment]
This will take some thought from us all; what do we right about first? is it our motivation to do such work?

**Comment by domhoward14** [comment]
Expanding off your idea maybe we make an about page describing our personal careers and goals ?

As for our first blog I have a couple ideas show below

-  Pros and Cons of security Certs
-  Why CISO's should have knowledge about technical implementations and not just purely management experience
- Starting on our OSCP Journey

**Comment by B3NLADEN** [comment]
ok; i like the above content! what about writing an original post just to state what we intend to accomplish with the establishment of our company.
- teach noobs
- instruct cyber professionals on the technical implementation of countermeasures
- the importance of compliance (strategy / gov)
ill keep going through this; and bring to mind some other ideas

**Comment by domhoward14** [comment]
That does seem very fitting for our first blog post
