### ISSUE TITLE
WordPress 

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#12]
Wordpress needs to be operational prior to begining this OSCP.

**Comment by B3NLADEN** [comment]
This epic is meant to maintain task associated with preparing the blog for functionality when the new year begins. Lets get started!

**Comment by B3NLADEN** [comment]
![current cost overview](https://user-images.githubusercontent.com/32402983/32211386-a661479e-bde8-11e7-816d-acec953e60a8.png)

**Comment by B3NLADEN** [comment]
@domhoward14 ; please see the above cost breakdown structure. we can go through this tomorrow. not too bad of a start up cost for everything; if we choose to go this route.

**Comment by domhoward14** [comment]
So I think that this is the best bang for our buck that we are going to get. Check this link (https://www.hostgator.com/web-hosting). I think the best plan for us to get is their "Baby Plan". It's already optimized to support Wordpress through the cPanel GUI. I'm ready to get this one, but just want to confirm some things with you guys on momday before moving forward.

**Comment by domhoward14** [comment]
Sent an email with credentials for our website. Check it out and let me know if you have any login questions.

**Comment by B3NLADEN** [comment]
Got into the management portion of the website. Everything is GUI based as you stated previously! Pretty cool man, pretty cool! Im excited we have that we have the website up and running! We are making awesome progress through the accomplishment of these task. @domhoward14 I will be sending you a link in your email for the dropbox to place the reciept for your expenses. Also, both of you all have access to this folder and this is where the logo and all accompaning files exist. This task is not completed as there remains the social media backdrop out for upgrade but as soon as that is done the task will be close. @domhoward14 please close any associated task! 

Bang bang!

**Comment by domhoward14** [comment]
Cool glad to hear ! And I'm about to add the expenses to that folder right now. Also @dominate2324 is it too late to have modifications made to the some of the logos ? That point Richard brought up I thought was good and we should have one that says technologies or engineering on it as well, especially for our stationary stuff.

**Comment by B3NLADEN** [comment]
@domhoward14  let me jump on portal right now with them and see if i can request an adjustment to the stationary. we may need to get on a call so that we can be specific about the request. im going to call you in like 5 mikes! 
![source_07nov17_1755_b38815_1](https://user-images.githubusercontent.com/32402983/32526129-bb1c6f98-c3f5-11e7-9a8c-b8c3b296ee69.jpg)

**Comment by Kungfurico** [comment]
That looks tight! Now the thing is getting the ficticous name through
Sunbiz... But I wouldn't recommend right now because it has to be attached
to brick and mortar. (Physical location)... But knowing you two, you
probably already checked it out. Remember to add Tech or Technology when
you officially sign up for the name...

**Comment by domhoward14** [comment]
@Kungfurico Trav said that the designer gave him the design file that we can easily open it up and edit how we want.. so maybe you can put your designer skills back to use and add the "Technologies" wording in addition to the logo !

**Comment by Kungfurico** [comment]
Cool, that sounds good!
