### ISSUE TITLE
Discuss Business formation

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#2]

**Comment by domhoward14** [comment]
I'm going to send some documents to you guys just for reading material at this point, but in the future will be very important in forming a contracting firm. 

I also found out that the VA offers free training for Vets trying to do what we are doing. I believe they have a SBA division that is responsible for this. If one of you guys could look more into this I think that this could be very beneficial.

**Comment by B3NLADEN** [comment]
ive already posted this info in the links tab over the git repository. i will show it to you later on today! 

https://github.com/domhoward14/Hacker_Lessons/blob/master/Tasking_Docs/Business_Starting_Links
