### ISSUE TITLE
Develop a training plan

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#3]

**Comment by B3NLADEN** [comment]
2017
===================
Travis: 
      - Linux Essentials (Almost done on my training on LA) 

Eric:
      - Linux Essentials
      - AWS Certified Solutions Architect (Associate Level)
      
Richard (Pending....):


2018 
===================
Travis: 
      - OSCP
      - LCIC1 101 Admin Cert
      - LCIC1 102 Admin Cert      
      - 8570 cert (maybe CEH) 
      - Start registering for Grad School (Maybe)

Eric:
      - OSCP
      - RedHat Cert
      - Start giving technical speeches at local events
      - Generate a Python course
      - Write a published white paper

Richard (Pending....):

#LEGGO

**Comment by domhoward14** [comment]
Team Goals:
========================
      - Make Social media Accounts 
            - Facebook
            - Twitter
            - Linkedin ???
            - Instagram ????

**Comment by B3NLADEN** [comment]
I like Instagram, Twitter and LinkedIn. Do you really think Facebook will be required? I'd like to participate in the paper, if you will have me onboard.

**Comment by B3NLADEN** [comment]
Twitter is done

**Comment by B3NLADEN** [comment]
I also have a email account that I am using to centralize everything from; I will be pushing you the creds

**Comment by Kungfurico** [comment]
# 2017
Rick:
CEH exam

# 2018
Rick:
OSCP
CompTIA Linux+(Possible)
