### ISSUE TITLE
Select individual Niche'

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#4]

**Comment by B3NLADEN** [comment]
RA / Governance & Compliance (Done)

**Comment by domhoward14** [comment]
After having a talk with Trav think this might be a idea worth discussing. Cyber Security insurance, combined with Written Information Security Plans (WISPs) becoming a regulated must have, and implementing network services could be a very lucrative package that we could offer to small and mid-size businesses. Check the link out below !

- www.datacenterjournal.com/ten-things-need-know-cybersecurity-insurance/
- www.msspalert.com/cybersecurity-markets/americas/can-main-street-cybersecurity-act-protect-small-businesses/
