### ISSUE TITLE
Review the about tab of the Wordpress site

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#6]
Eric, 
       I have written the about portion of the wordpress site. Please go through it and edit it if needed. I am about to add more issues later on today. let me know what you think.

**Comment by domhoward14** [comment]
Dang I like that !! I honestly don't want to change anything except for the theme so there isn't so much white space, but that will be done at a later date (after we have a logo and etc).

**Comment by B3NLADEN** [comment]
Yea I been thinking about we will need to do beyond this. Looks like you already beat me to setting up the task. We gotta setup all of website information for Twitter, Facebook etc

**Comment by domhoward14** [comment]
I talked about this in another task, but should we talk about our selves as well in this tab ?

**Comment by B3NLADEN** [comment]
I think we should have a founders page; this page is about what we wish to accomplish as N2. Or we could just flip this to a combo page and include our mission and founders info??

**Comment by domhoward14** [comment]
I have an idea we could do for this page. I'll show you today during lunch the layout i'm thinking of.
