### ISSUE TITLE
Refine Theme

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#7]

**Comment by B3NLADEN** [comment]
this one may take a large portion of time; we could also relegate this to a developer from fiveer and focus on our content; just a thought

**Comment by domhoward14** [comment]
I like the Fiverr idea, or we could just use a free theme or one of those drag and drop websites. I'm not trying to touch any CSS though lol !

**Comment by B3NLADEN** [comment]
Found aa pretty decent content creator on fiverr for both WP and the logo; the next step is prolly to get the final domain name. Ill chop it with you tomorrow about this one

**Comment by domhoward14** [comment]
hmm that sounds promising. Look forward to hearing more about this one.
