### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#8]

**Comment by B3NLADEN** [comment]
this will require some bread; we need to find out how we will approach this

**Comment by domhoward14** [comment]
I think I told you guys before, but I know someone who does this stuff. I'll inform him about the logo this week and hopefully have an update for it  by11/7/2017.

**Comment by B3NLADEN** [comment]
@domhoward14 Ite'; you let's look into that. And let through some targets behind this. There are a few bidding sites as well as the freelancer site fiverr that can be used to create the logo

**Comment by domhoward14** [comment]
Thats true, and if we do a couple of them it would cost some money but we would have options and could choose the best one.

**Comment by Kungfurico** [comment]
Hmmm ok

**Comment by B3NLADEN** [comment]
This task has been completed; the logo's have been loaded into the N2 share drive along with the accompanying stationary. there is one file missing from the stationary which i requested, we should receive that next week.  also, the social media templates are also in the works. they could not use the picture that i sent so i requested that they make something similar to it so that the file will belong to us solely; i will be closing this once all files have been rendered.

**Comment by B3NLADEN** [comment]
all of the final files have been rendered and exist in the N2 drive file that I created. This task is now closed.
