### ISSUE TITLE
Link Social Media Accounts

### ISSUE THREAD

**Issue by B3NLADEN** [domhoward14/Hacker_Lessons#9]

**Comment by B3NLADEN** [comment]
again busy work; too easy. We have a twitter; we need iG and lKNDIN

**Comment by domhoward14** [comment]
I can definitely complete this during this weekend. Question I have is though what content are we going to deliver on each social media account ? For example LinkedIn will be for reposting good articles and publishing our papers, but how are we going to use IG and Twitter ?

**Comment by B3NLADEN** [comment]
Twitter will be used to create short, thoughtful post aaand to engage with other thought leaders in our community. I'm assuming that IG and Facebook can just be used for web presence. Ill do some research now to see if any other small firms maintain such

**Comment by domhoward14** [comment]
Yeah I was going to do the same. That should inspire some good ideas and paths to go down.
